apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/prometheus  # ローカルディスクを使用する場合（ここでは例として/mnt/dataを指定）
  volumeMode: Filesystem
